### ISSUE TITLE
Incorporating Firebase

### ISSUE THREAD

**Issue by ekitten** [SCCapstone/TheB-Team#10]

**Comment by bcarter98** [comment]
Adding trucks is no longer necessary, changed to implementing firebase

**Comment by josemvidal** [comment]
I don't see any way in which you have incorporated firebase. There is no way for the user to enter some data into firebase and then get it back later.

**Comment by LiamAOlson** [comment]
We showed in the video demo that on the requirements page we enter in data and it shows up on the firestore database. This was only supposed to have 10% functionality.

**Comment by josemvidal** [comment]
The first thing you need to do to prove that a backend is working is let the user enter some data and get it back, from your backend. The first half of that is the user enters data and the programmer goes to the database to check that it is there. The second have is for the app to fetch that data back and display it to the user. You (might be, if you are telling the truth, which I cannot verify, video is very easy to splice) be halfway there.

**Comment by bttorres** [comment]
You're unable to verify if our app actually writes data to the backend? If you believe our video is spliced, are you unable to access the code to verify?

**Comment by josemvidal** [comment]
Did you write the code that fetches the data the user entered into firebase and displays that data to the user?

**Comment by bttorres** [comment]
It does not fetch the data and display it back to the user. It only writes the data to firebase. Your message made it seem as if you have doubts on whether or not we even did that much. If that is the case, you can check the code (if you are able to access it). We did not display the data back to the user because we felt we did not need to. The "Proof of Concept Milestone" states that we only need to "implement at least 10% of the final functionality" and we felt that we accomplished that.

**Comment by josemvidal** [comment]
Getting data form the database and showing it to the user is important. User enters data, gets stored in database, user fetches some data from database and sees it it in a pretty display. Reading/Displaying(Views) and Writing are different things programmatically.

https://capstone.cse.sc.edu/milestone/proof-of-concept/

> exercise all the external APIs you plan to use, that means writing/reading from a file if you plan to use files, pinging the GPS if you plan to use GPS, sending a tweet if you plan to use Twitter, **read/writing to the database** if you plan to use a database, etc.

**Comment by bttorres** [comment]
Ok, it is understood that reading/displaying and writing are different. We were uncertain about the wording. We felt that "read/writing" meant "reading OR writing" instead of "reading AND writing." We did not do any reading/displaying from the database and we will change that in the future but if there is any doubt that we wrote to the database, the code can be looked at to verify.
