### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by johnburton0517** [SCCapstone/TheB-Team#112]
Are A and B aloud to be negative?

![image](https://user-images.githubusercontent.com/71100259/162635548-a616e86b-ca9c-4ddf-b940-f848b7879cc6.png)

**Comment by bcarter98** [comment]
Like the other issue regarding the A and B variables, these were random variables created by someone using the admin login and were created so that they were allowed to be negative. For the normal rules that we would have in the database (before they were deleted) the values would be set so that they could not be negative.

**Comment by LiamAOlson** [comment]
I made it so that no input is allowed to have a negative value
