### ISSUE TITLE
Calculator Contains Abmigous Input Boxes

### ISSUE THREAD

**Issue by RussellTHumphries** [SCCapstone/TheB-Team#121]
Point A: 123 Fifeshire, Columbia, SC
Point B: 124 Fifeshire, Columbia, SC

Additional Inputs appear when inputs are accepted.

The inputs do not appear to have a consistent impact on the calculated price

![Calculator Test](https://user-images.githubusercontent.com/35664235/163732486-520cc2e5-48b6-4fef-8e4c-54722dbd7038.JPG)
![Calculator Test Input 1](https://user-images.githubusercontent.com/35664235/163732488-f2efaeb1-bddf-4193-90fd-fc2d7e1d2b99.JPG)
![Calculator Test Input 2](https://user-images.githubusercontent.com/35664235/163732489-3048e577-8594-4f67-b831-5dab53dfddea.JPG)

The numbers used in the additional inputs where as follows:
Attempt 1:
A: Empty
B: Empty

Attempt 2:
A: 1
B: 1

Attempt 3: (As I believe is described by the Rules/Regulations)
A: 11
B: 15

**Comment by bcarter98** [comment]
These A and B rules were created when someone was testing out the admin account and the correct rules (length, width, height, etc) were deleted. We will get to adding the proper rules back and deleting the A and B rules asap. The weird values you are getting here are just because of the A and B rules not making sense.
